vich_uploader:
    db_driver: orm

    mappings:
        cmrs:
            upload_destination: '%kernel.project_dir%/var/uploads/cmrs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        logos:
            uri_prefix: '/uploads/logos'
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
